### ISSUE TITLE
Broken in processing 4 python mode

### ISSUE THREAD

**Issue by liavkoren** [jdf/peasycam#44]
I realize there hasn't been a peasycam release in about five years, **but!** If you feel like blowing the dust off the code...

```
add_library('peasycam')


def setup():
    size(800, 600)

def draw():
    pass
```

yields 

```
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at jycessing.LibraryImporter.addJarToClassLoader(LibraryImporter.java:315)
	at jycessing.LibraryImporter.recursivelyAddJarsToClasspath(LibraryImporter.java:164)
	at jycessing.LibraryImporter.addLibrary(LibraryImporter.java:140)
	at jycessing.LibraryImporter$1.__call__(LibraryImporter.java:82)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at org.python.pycode._pyx117.f$0(QuadRendering.pyde:1)
	at org.python.pycode._pyx117.call_function(QuadRendering.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.pycode._pyx116.f$0(/var/folders/4x/9g74c86d7k1bzcqy50r_xdcc0000gn/T/QuadRendering9422620782247159764/QuadRendering.pyde:96)
	at org.python.pycode._pyx116.call_function(/var/folders/4x/9g74c86d7k1bzcqy50r_xdcc0000gn/T/QuadRendering9422620782247159764/QuadRendering.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at jycessing.PAppletJythonDriver.processSketch(PAppletJythonDriver.java:233)
	at jycessing.PAppletJythonDriver.findSketchMethods(PAppletJythonDriver.java:613)
	at jycessing.Runner.runSketchBlocking(Runner.java:399)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by b-mq** [comment]
+1
